spring:
  application:
    name: CASH_RECEIPT
  config:
    import: classpath:application-secrets.yml
  datasource:
    url: jdbc:postgresql://localhost:5432/purchases
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
bot:
  name: ${BOT_NAME}
  token: ${BOT_TOKEN}
server:
  port: 8090